### ISSUE TITLE
Cache example doesn't work

### ISSUE THREAD

**Issue by TomSeldon** [zohararad/sails-rest#44]
* **Sails version:** v0.11.0
* **sails-rest version:** v0.0.4

I've followed the example shown to get a cache (specifically, `lru-cache`) working with this module, and it throws an error. It seems that at some point between creating the cache and it being used in `SailsRest.js`, it's being stripped of its methods (`get`/`set`/`del`), although other properties of the object (e.g. `maxAge`) are still there.

Example code:

```javascript
// config/cache.js

var LRU = require('lru-cache');
var options = {
  max: 100, // Max number of items in cache
  maxAge: 60 * 1000 // Max age in ms
};
var cache = LRU(options);

module.exports.cache = cache;

// typeof cache.get === 'function'
```

```javascript
// SailsRest.js 

// Line: 236 errors

    // Retrieve data from the cache
    if (methodName === 'find') {
      r = cache && cache.engine.get(uri); // Line 236: cache.get is undefined
    }
```

I'm unsure what the cause of this problem is, including if the problem is actually because of a bug with `sails-rest` or Sails itself.

But, for the benefit of anyone else running in to this problem; I've worked around it by altering `config/cache.js` to the following:

```javascript
var LRU = require('lru-cache');
var options = {
  max: 100, // Max number of items in cache
  maxAge: 60 * 1000 // Max age in ms
};
var cache = LRU(options);

module.exports.cache = {
  get: function(key) {
    return cache.get(key);
  },

  set: function(key, val) {
    return cache.set(key, val);
  },

  del: function(key) {
    cache.del(key);
  }
};
```

This issue is *probably* caused (though I haven't checked) by `lru-cache` using non-enumerable properties for the above methods, which aren't being copied if the object is being copied/extended. Just a guess...

**Full stack trace**:
```
error: Unable to parse HTTP body- error occurred :: 'TypeError: Object #<Object> has no method \'get\'\n    at makeRequest (/path/to/app/node_modules/sails-rest/SailsRest.js:236:33)\n    at Object.module.exports.adapter.find (/path/to/app/node_modules/sails-rest/SailsRest.js:355:7)\n    at module.exports.find (/Users/Tom/.nvm/v0.10.33/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/dql.js:121:13)\n    at module.exports.findOne (/Users/Tom/.nvm/v0.10.33/lib/node_modules/sails/node_modules/waterline/lib/waterline/adapter/dql.js:161:10)\n    at _runOperation (/Users/Tom/.nvm/v0.10.33/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:400:29)\n    at run (/Users/Tom/.nvm/v0.10.33/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/operations.js:69:8)\n    at bound.module.exports.findOne (/Users/Tom/.nvm/v0.10.33/lib/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:66:16)\n    at bound [as findOne] (/Users/Tom/.nvm/v0.10.33/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)\n    at passport.use.LocalStrategy.usernameField (/path/to/app/config/passport.js:11:8)\n    at pass (/path/to/app/node_modules/passport/lib/authenticator.js:353:9)\n    at Authenticator.deserializeUser (/path/to/app/node_modules/passport/lib/authenticator.js:358:5)\n    at SessionStrategy.authenticate (/path/to/app/node_modules/passport/lib/strategies/session.js:49:28)\n    at attempt (/path/to/app/node_modules/passport/lib/middleware/authenticate.js:341:16)\n    at Object.authenticate [as handle] (/path/to/app/node_modules/passport/lib/middleware/authenticate.js:342:7)\n    at next (/Users/Tom/.nvm/v0.10.33/lib/node_modules/sails/node_modules/express/node_modules/connect/lib/proto.js:169:15)\n    at Object.initialize [as handle] (/path/to/app/node_modules/passport/lib/middleware/initialize.js:62:5)'
```

**Comment by zohararad** [comment]
@TomSeldon thanks for this. I'll try and modify the example code to reflect your workaround.

I too think it's probably due to something with the lru-cache module, as in my initial implementation it worked well, so the API must've changed since then.
