### ISSUE TITLE
Error loading the adapter

### ISSUE THREAD

**Issue by abdulhamid-alattar** [zohararad/sails-rest#74]
error: A hook (`orm`) failed to load!
error: TypeError: Cannot read property 'config' of undefined
    at validateModelDef (/usr/lib/node_modules/sails/node_modules/sails-hook-orm/lib/validate-model-def.js:108:84)
    at /usr/lib/node_modules/sails/node_modules/sails-hook-orm/lib/initialize.js:218:36
    at arrayEach (/usr/lib/node_modules/sails/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/usr/lib/node_modules/sails/node_modules/lodash/index.js:3345:13)
    at Array.async.auto._normalizeModelDefs (/usr/lib/node_modules/sails/node_modules/sails-hook-orm/lib/initialize.js:216:11)
    at listener (/usr/lib/node_modules/sails/node_modules/sails-hook-orm/node_modules/async/lib/async.js:605:42)
    at /usr/lib/node_modules/sails/node_modules/sails-hook-orm/node_modules/async/lib/async.js:544:17
    at _arrayEach (/usr/lib/node_modules/sails/node_modules/sails-hook-orm/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/usr/lib/node_modules/sails/node_modules/sails-hook-orm/node_modules/async/lib/async.js:543:13)
    at processImmediate [as _immediateCallback] (timers.js:383:17) [TypeError: Cannot read property 'config' of undefined]
error: Could not load Sails.
error: Are you using the latest stable version?

just installing at the latest sailsjs version and using the example

**Comment by zohararad** [comment]
Could it be an unrelated issue? Is Sails working properly with another Waterline adapter?

**Comment by abdulhamid-alattar** [comment]
Yup. I have elastic search adapter and it's working fine in the same project

**Comment by zohararad** [comment]
I need to see some code to try and debug. Can you post a gist or paste here in the issue?

**Comment by abdulhamid-alattar** [comment]
Installed it on a new installation of SailsJS and it worked. Will close this issue, and thanks for the response . will check what could be the cause of the conflict and will update you if it has something to do with it. Many thanks

**Comment by zohararad** [comment]
No worries. Happy to look into things if something is broken in sails-rest itself
